# Site settings
title: Shawn's Blog
email: shawn.leberknight@gmail.com
description: "My thoughts about life."
baseurl: "/blog"
url: "http://shawnleberknight.com/blog"
twitter_username: shawnlknight
github_username:  shawnlknight

# Build settings
markdown: kramdown
permalink: pretty
