# Site settings
title: Code To Live By
email: shawn.leberknight@gmail.com
description: ""
baseurl: "/blog"
url: "http://shawnleberknight.com/blog"
twitter_username: shawns_beard
github_username:  shawnlknight
home: "http://shawnleberknight.com/blog"
me: "http://shawnleberknight.com"
paginate: 5
# paginate_path: "/blog/page:num"


# Build settings
markdown: kramdown
redcarpet:
  extensions: ["smart", "tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
permalink: none
host: localhost

highlighter: rouge

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
