# Site settings
title: Code To Live By
email: shawn.leberknight@gmail.com
description: ""
baseurl: "/blog"
url: "http://shawnleberknight.com/blog"
twitter_username: shawnlknight
github_username:  shawnlknight
home: "http://shawnleberknight.com/blog"
me: "http://shawnleberknight.com"
paginate: 5
# paginate_path: "/blog/page:num"


# Build settings
markdown: redcarpet
permalink: pretty
host: localhost

highlighter: pygments

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
